"""empty message

Revision ID: 6ba3430b1354
Revises: 98a56b0db50a
Create Date: 2026-06-30 14:00:40.345882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6ba3430b1354'
down_revision: Union[str, Sequence[str], None] = '98a56b0db50a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_deptmodel',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('leader_id', sa.Integer(), nullable=True),
    sa.Column('leader_name', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='最后修改时间'),
    sa.ForeignKeyConstraint(['pid'], ['t_deptmodel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    mysql_engine='InnoDB'
    )
    op.create_table('t_menumodel',
    sa.Column('number', sa.Integer(), nullable=False, comment='排序数字'),
    sa.Column('url', sa.String(length=200), nullable=True, comment='前端路由访问地址，可以没有'),
    sa.Column('name', sa.String(length=20), nullable=False, comment='菜单显示的名称'),
    sa.Column('is_parent', sa.Boolean(), nullable=False, comment='是否为顶级菜单'),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='最后修改时间'),
    sa.ForeignKeyConstraint(['pid'], ['t_menumodel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('t_rolemodel',
    sa.Column('name', sa.String(length=20), nullable=False, comment='角色的名字'),
    sa.Column('remark', sa.String(length=500), nullable=False, comment='角色的备注'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('t_permissionmodel',
    sa.Column('name', sa.String(length=20), nullable=False, comment='权限名字'),
    sa.Column('is_interface', sa.Boolean(), nullable=False, comment='是否为接口'),
    sa.Column('url', sa.String(length=200), nullable=True, comment='接口访问地址，可以没有'),
    sa.Column('method', sa.String(length=20), nullable=True, comment='接口的请求方法，可以没有'),
    sa.Column('menu_id', sa.Integer(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='最后修改时间'),
    sa.ForeignKeyConstraint(['menu_id'], ['t_menumodel.id'], ),
    sa.ForeignKeyConstraint(['pid'], ['t_permissionmodel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('t_role_permission',
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['t_permissionmodel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['t_rolemodel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('permission_id', 'role_id')
    )
    op.create_table('t_user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['t_rolemodel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['t_usermodel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.drop_index(op.f('username'), table_name='t_xx')
    op.drop_table('t_xx')
    op.add_column('t_usermodel', sa.Column('dept_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 't_usermodel', 't_deptmodel', ['dept_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_usermodel', type_='foreignkey')
    op.drop_column('t_usermodel', 'dept_id')
    op.create_table('t_xx',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True, comment='用户的手机号码'),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=True, comment='用户的邮箱地址'),
    sa.Column('real_name', mysql.VARCHAR(length=50), nullable=True, comment='用户的真实名字'),
    sa.Column('icon', mysql.VARCHAR(length=100), nullable=True, comment='用户的展示头像'),
    sa.Column('create_time', mysql.DATETIME(), nullable=False),
    sa.Column('update_time', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('username'), 't_xx', ['username'], unique=True)
    op.drop_table('t_user_role')
    op.drop_table('t_role_permission')
    op.drop_table('t_permissionmodel')
    op.drop_table('t_rolemodel')
    op.drop_table('t_menumodel')
    op.drop_table('t_deptmodel')
    # ### end Alembic commands ###
