"""数据库初始化

Revision ID: 98a56b0db50a
Revises: 
Create Date: 2026-06-28 17:33:43.397989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98a56b0db50a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_usermodel',
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='用户的手机号码'),
    sa.Column('email', sa.String(length=50), nullable=True, comment='用户的邮箱地址'),
    sa.Column('real_name', sa.String(length=50), nullable=True, comment='用户的真实名字'),
    sa.Column('icon', sa.String(length=100), nullable=True, comment='用户的展示头像'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_usermodel')
    # ### end Alembic commands ###
